name: dbt_step_by_step

profile: dbt_sbs

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  # Builds seeds into '<your_schema_name>_raw'
  dbt_step_by_step:
    +schema: raw

models:
  dbt_step_by_step:
    +persist_docs:
      relation: true
      columns: true
    staging:
      +materialized: view
    airline:
      +materialized: table
    marts:
      +materialized: table
